server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;

        # สำคัญสำหรับ video streaming
        types {
            video/mp4 mp4;
        }

        add_header Accept-Ranges bytes;
    }
}
