server {
    listen 80;
    server_name localhost;

    location / {
        # ต้องชี้ไปที่ IP ของ Origin Server ใน Mininet
        proxy_pass http://10.0.0.100; 
        
        # ตั้งค่า Cache
        proxy_cache_valid 200 302 10m;
        add_header X-Cache-Status $upstream_cache_status;
    }
}
